---
- hosts: all
  become: False
  gather_facts: False
  tasks:
    - name: Installing the web server.
      yum:
        name: httpd
        state: latest

    - name: Copy index file.
      copy:
             src: index.html
             dest: /var/www/html/index.html
             mode: 644
             owner: apache
             group: apache
    - name: staring httpd service
      service:
        name: httpd
        state: restarted
